### PR TITLE
Create the feedback button and style it with appropriate style.

### PR DESCRIPTION
**Pull request by dheerajsingh01**
Issue #20  

I create a feedback button in the footer section and connect it with form.html 
I also update the form.js like if anybody submit the form they will redirect on the home or index.html after 2 seconds.
Screenshot 2024-10-07 123944
Screenshot 2024-10-07 124006

### CODE REVIEW

**Comment by JollyJolli** [comment]
I think I solved the merge error

**Comment by JollyJolli** [comment]
Perfect! Thanks for contributing!

**Comment by dheerajsingh01** [comment]
Thanks a lot 👍

**Comment by JollyJolli** [comment]
Thank you!

**Pull request merged**
