### PR TITLE
Update contributors.json

### PR DESCRIPTION
**Pull request by Karthikeya914**

### CODE REVIEW

**Review by JollyJolli — CHANGES_REQUESTED** [review]
There is a coma missing before. example:
},
{
"name": "happy"
}

**Review by Karthikeya914 — COMMENTED** [review]
done added a comma thank you !

**Comment by JollyJolli** [comment]
Thanks for contributing my friend!

**Comment by Karthikeya914** [comment]
my pleasure!!

**Comment by Karthikeya914** [comment]
Thank you !

**Pull request merged**
