### PR TITLE
fixed invalid path

### PR DESCRIPTION
**Pull request by exilonium**

### CODE REVIEW

**Review by JollyJolli — COMMENTED** [review]
Good addition

**Comment by JollyJolli** [comment]
hey there can you please solve the branch conflicts?

**Comment by exilonium** [comment]
ok let me try

**Comment by exilonium** [comment]
idk how but i think i fixed it
:)

**Comment by JollyJolli** [comment]
Perfect! Thank you!

**Comment by exilonium** [comment]
i feel like this commit looks cursed
should we revert it?

**Pull request merged**
