### PR TITLE
fix: logo redirects to homepage

### LINKED ISSUE #152: [BUG]: Logo doesn't redirect to the homepage
**Describe the bug**
The current website has two pages, home and forms. If I go to the form page, then I cannot go back to home by clicking on the logo as it points to '#' . I noticed much later that the form button is replaced with home. But I do not think this is good in terms of user experience. 

**Current behavior**
https://github.com/user-attachments/assets/387e4a5c-1a00-4207-a1f7-4915337dd5e4

**Expected behavior**
https://github.com/user-attachments/assets/7d44a0de-55cd-479d-b287-d881a20c5cb5

**Additional context**
I would like to raise a PR on this if the maintainers agree.

### PR DESCRIPTION
**Pull request by nafisreza**
fixes #152

### CODE REVIEW

**Comment by JollyJolli** [comment]
Oh there! Thanks for addding this! But there is a issue! The host (Vercel ) is deploys the SRC file as the main file, so when you are making the way back to "src/index.html" it finds a issue and goes no where.
image

**Comment by nafisreza** [comment]
My bad. @JollyJolli I didn't know only src folder was deployed. I was testing on my localhost. I should just change it to ' /index.html '

**Review by JollyJolli — CHANGES_REQUESTED** [review]
Please change the href to only ./index.html (it may dont work on your localhost but lets try)

**Comment by JollyJolli** [comment]
> My bad. @JollyJolli I didn't know only src folder was deployed. I was testing on my localhost. I should just change it to ' /index.html '

Yes please, let's try that

**Comment by nafisreza** [comment]
I have pushed the changes. Could you please take a look now?

**Comment by JollyJolli** [comment]
Perfect! Thank you!

**Review by JollyJolli — APPROVED** [review]
Works perfect

**Comment by JollyJolli** [comment]
Have a nice day!

**Pull request merged**
