### PR TITLE
fix : changes made in about us section #162

### PR DESCRIPTION
**Pull request by ishan657**
**Pull Request Title**:  #162
Add "About Us" Section in a Card

**Pull Request Description**:
- Encapsulated the entire "About Us" section inside a card component for better UI structure and visual separation.
- Updated CSS styles to ensure consistent layout within the card.

Screenshot 2024-10-24 042513

### CODE REVIEW

**Comment by ishan657** [comment]
Please review the changes I have made and let me know if there is something wrong. I will fix it right away
ThankYou

**Comment by JollyJolli** [comment]
Hello there! Thanks for contributing, i love the result but there is something that you could add.
Just add the same background as the other cards and we are ready! Thank you.
image

**Comment by JollyJolli** [comment]
Perfect! Thank you 🫶🏻

**Comment by ishan657** [comment]
Thankyou @JollyJolli 
For giving a chance to contribute on this issue, it was such a nice experience for me.
just one doubt should i delete the branch since my pr has been merged?

**Comment by JollyJolli** [comment]
Yeah you can do it, there isn't a problem 🫶🏻

**Pull request merged**
