### PR TITLE
updated a few things check them out

### PR DESCRIPTION
**Pull request by TechnicallyKiller**
1. Theme Switcher Implementation (app.js & style.css):
Added Halloween Theme:
New styles for Halloween mode were added, such as dark backgrounds, spooky orange and red colors, and a Halloween background image (halloween-bg.png).
Theme Switching Logic:
Implemented functionality to switch between Light, Dark, and Halloween modes in sequence.
Automatic Activation:
Halloween mode automatically activates on October 31st via the checkHalloweenDate function in app.js.
2. UI Fixes:
Resolved Duplicate Theme Toggle Buttons:
Identified and removed the extra theme toggle button in the HTML.
Displayed Halloween Footer Message:
Fixed the issue where the Halloween footer message ("Have a spooky Halloween! 👻") was not showing by ensuring it appears when Halloween mode is active.

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey there! Thanks for this contribution! Just something, can you please remove the text that says "App Name"?

**Comment by TechnicallyKiller** [comment]
suree let me fix this

**Comment by TechnicallyKiller** [comment]
check noww!!

**Comment by JollyJolli** [comment]
Thanks for contributing!

**Pull request merged**
