### PR TITLE
[Bug] contributors.json issue fixed

### PR DESCRIPTION
**Pull request by wasif1**
Comma issue is fixed

### CODE REVIEW

**Comment by wasif1** [comment]
Hi, Please assign this to me and merge Thanks

**Comment by Phanty78** [comment]
please delete your idea file first @wasif1

**Review by Phanty78 — CHANGES_REQUESTED** [review]
please delete your idea file first @wasif1

**Comment by wasif1** [comment]
Done. Please check

**Review by Phanty78 — APPROVED** [review]

**Pull request merged**
