### PR TITLE
- Code cleaning in app.js and contributors.js

### PR DESCRIPTION
**Pull request by Phanty78**
- Rewrite of section array to automatize it

### CODE REVIEW

**Comment by JollyJolli** [comment]
Thanks for contributing again jajaj

**Comment by Phanty78** [comment]
Your welcome, do you have an Twitter ?

**Comment by JollyJolli** [comment]
Yes! But i barly use i. `@kuikilod`

**Comment by JollyJolli** [comment]
Whats your @?

**Comment by Phanty78** [comment]
@anotherhappydev
________________________________
De : Jolly ***@***.***>
Envoyé : jeudi 17 octobre 2024 16:24
À : JollyJolli/HacktoberWall ***@***.***>
Cc : Mael Donnart ***@***.***>; Author ***@***.***>
Objet : Re: [JollyJolli/HacktoberWall] - Code cleaning in app.js and contributors.js (PR #106)


Whats your @?

**Comment by JollyJolli** [comment]
Perfect! I will follow you rn!

**Pull request merged**
