### PR TITLE
Create many_language

### PR DESCRIPTION
**Pull request by nehaaaah123**
By implementing multi-language support, the website will become more accessible to non-English speakers, broadening the audience and enhancing user experience. This approach facilitates engagement with diverse user groups, promoting inclusivity and ensuring that all users can navigate and understand the content effectively.

### CODE REVIEW

**Review by JollyJolli — COMMENTED** [review]
I dont understand what you made (?

**Comment by JollyJolli** [comment]
The idea is that the website have multi-support languague.

**Review by Phanty78 — CHANGES_REQUESTED** [review]
This code does not add any functions to the site.
What would you like to do?

**Comment by JollyJolli** [comment]
If you want you can send other PR.

**Pull request closed without merging**
