### PR TITLE
Aria labels, Alt text for images and tab key navigation added

### LINKED ISSUE #19: Add Accessibility Features
Implement accessibility features to make the website usable for all individuals, including those with disabilities.

### Tasks
- [ ] Use ARIA roles and attributes to enhance screen reader support.
- [ ] Ensure color contrast meets WCAG guidelines.
- [ ] Add keyboard navigation for all interactive elements.
- [ ] Provide alt text for images.

### Brief Info
These features will improve usability for people with disabilities and comply with accessibility standards.

### Additional Context
Enhancing accessibility is vital for inclusivity and can broaden the audience reach.

### PR DESCRIPTION
**Pull request by Pranathi1314**
Aria labels have been added in the code where they weren't present before 
Alt text has been added for the background, logo and buttons
Tab key navigation has been enabled to allow navigating between buttons on the website by using the "Tab" key.
After my changes the site works fine on my PC : 
pr4

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey there! Give me around 10 minutes to review, thanks for contributing!

**Review by JollyJolli — APPROVED** [review]
Is ready to merge!

**Comment by JollyJolli** [comment]
Thanks for contributing! Happy hacktoberfest

**Comment by Pranathi1314** [comment]
Thank you!

**Comment by Pranathi1314** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
