### PR TITLE
Fixed navbar in mobile 

### PR DESCRIPTION
**Pull request by PAVAN507-STAR**
Fixed the navabr overlapping issue in mobile by adding a toggle menu button to the right edge of the screen.Added different blurred  backgrounds for black and white theme.Made sure the look on pc remained same.Closes issue #161.
image
image
image

### CODE REVIEW

**Review by Phanty78 — CHANGES_REQUESTED** [review]
Code seems good.
Please don't erase all commentary in CSS file.

**Comment by PAVAN507-STAR** [comment]
> Code seems good. Please don't erase all commentary in CSS file.
Yeah sure . @Phanty78 show i raise another pr.I'm new to git and open source so correct if im wrong

**Comment by JollyJolli** [comment]
It's just like I wanted! Thank you! But please solve the changes that Phanty78 asked for.

**Comment by PAVAN507-STAR** [comment]
Hii @JollyJolli .Restored the comments in css file as u said.Btw sorry for the delay had some college stuff to do(exams).

**Review by Phanty78 — APPROVED** [review]
Good for me, I approve it.

**Comment by Phanty78** [comment]
Just fix the conflict and push the corrected code and i will merge it. @PAVAN507-STAR

**Comment by Phanty78** [comment]
Oh : and don't forgot to minify the CSS please ;)

**Comment by PAVAN507-STAR** [comment]
Hii @Phanty78 .Done solved the conflicts

**Comment by JollyJolli** [comment]
I look it good but i will wait for Phanty's response cuz this is his issue

**Review by Phanty78 — APPROVED** [review]
Perfect, let's go !

**Pull request merged**
