### PR TITLE
fix (#20) : Implement a Feedback Mechanism

### PR DESCRIPTION
**Pull request by 28harshjadhav**
### Changes Made
- Created a simple feedback form that includes:
  - **Fields for Comments:** Users can submit their thoughts and suggestions.
  - **Fields for Contact Information:** Users can provide their email or contact number (optional).

- Implemented a thank you message that appears after form submission to acknowledge user input.

- Set up a system to collect and review the feedback submitted:
  - Established a database or storage mechanism for storing feedback.
  - Created an admin interface (if applicable) for reviewing submitted feedback.

### Testing
- Verified that the feedback form displays correctly on the website.
- Tested form submission to ensure that comments and contact information are stored accurately.
- Checked that the thank you message appears after successful submission.
- Reviewed the collected feedback for correct data storage and retrieval.

### Checklist
- [ ] Code changes are well-documented.
- [ ] All new and existing tests passed.
- [ ] UI/UX has been reviewed and approved.
- [ ] Changes are consistent with project guidelines.
- [ ] Merge conflicts have been resolved.

Screenshot 2024-09-30 203716

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey thank you for contributing! This is really great, thank you! I only have one question, where is the feedback stored?

**Comment by 28harshjadhav** [comment]
In  current code, the feedback data (comments and contact information) is only logged to the console and not being stored anywhere.

**Comment by JollyJolli** [comment]
Okey, you will continue with this?

**Comment by 28harshjadhav** [comment]
Currently could you please let me know if I am being considered as a contributor?

**Comment by JollyJolli** [comment]
Yeah of course, i will merge the PR but i want to know if you will continue continue in this or if i need to help with the feedback mechanism

**Pull request merged**
