### PR TITLE
I have created a cookie banner

### PR DESCRIPTION
**Pull request by swarupsahu08**
I have made cookie banner that would be visible whenever a new user visit the website and I have added the feature of enabling and disabling cookies

### CODE REVIEW

**Comment by JollyJolli** [comment]
This was quick jajaj

**Comment by JollyJolli** [comment]
Hey there! I think i solved the merge issues

**Comment by JollyJolli** [comment]
> I tried my best to complete it quickly hope that we can connect for someother projects too

I hope to contribute more with you! I will follow you

**Comment by swarupsahu08** [comment]
Thanks for the help bro

**Comment by JollyJolli** [comment]
thanks you for helping me! If you want you can star the project <3

**Comment by swarupsahu08** [comment]
> > I tried my best to complete it quickly hope that we can connect for someother projects too
> 
> I hope to contribute more with you! I will follow you

Yah thats great bro ,I am happy to collaborate with you

**Comment by swarupsahu08** [comment]
> thanks you for helping me! If you want you can star the project <3

yah sure Actually I forgot to star the repository

**Comment by JollyJolli** [comment]
Thanks! Im so close to the badge!

**Comment by JollyJolli** [comment]
The startuck (or something like that) badge that is when you have a repository with 16+ stars!
image

**Comment by JollyJolli** [comment]
> Hey can we connect on any social media like Twitter or linkedin

Maybe instagram?

**Comment by JollyJolli** [comment]
Weel my Twitter is `@kuikilod` but i rarely use it

**Comment by swarupsahu08** [comment]
> The startuck (or something like that) badge that is when you have a repository with 16+ stars!
> image
> 

ok got it

**Comment by swarupsahu08** [comment]
> Well my Twitter is `@kuikilod` but i rarely use it

Thats great I have followed you

**Comment by swarupsahu08** [comment]
> Well my Twitter is `@kuikilod` but i rarely use it

Lets connect there

**Comment by JollyJolli** [comment]
whats your @?

**Comment by swarupsahu08** [comment]
> whats your @?

mine is @Swarups08

**Comment by swarupsahu08** [comment]
> whats your @?

I have already followed you

**Comment by swarupsahu08** [comment]
Hey @JollyJolli  have you added hacktoberfest-accepted tag

**Comment by JollyJolli** [comment]
Sorry about that

**Comment by swarupsahu08** [comment]
> Sorry about that

no problem

**Pull request merged**
