### PR TITLE
Changed styles in sort-by menu

### PR DESCRIPTION
**Pull request by Heshan2691**
I minify the CSS code

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hello! The css isnt minify yet, just paste the CSS here: https://www.cleancss.com/css-minify/

**Comment by Heshan2691** [comment]
I minified the CSS using that tool and also check with my local machine

**Comment by JollyJolli** [comment]
It should be like this:
image

**Comment by JollyJolli** [comment]
I will do it dont worry, thanks for contributing!

**Pull request merged**
