### PR TITLE
update modal

### PR DESCRIPTION
**Pull request by mishrayush15**
I have updated the **Modal** which was previously done using ```alert()```. I have also made sure that whenever user clicks ***Surprise Me!*** button, the user must first close the Modal to again get a new Surprise after clicking the Surprise Me! button. I have tried to make the Modal look **clean** and **attractive** with simple and rounded box with decent design. I have made sure to cover all the tasks that you have requested. Kindly do let me know if this requires any other change, I will be more than happy to help you out.

### CODE REVIEW

**Comment by JollyJolli** [comment]
Bro this is awesome!!! Thanks for contributing

**Comment by JollyJolli** [comment]
But it cant be merged :((( can you pull the New changes of the repo?

**Comment by mishrayush15** [comment]
Sure mate I'll pull the new changes again. Glad that you liked my contribution ☺️☺️

**Comment by JollyJolli** [comment]
So I will wait for another PR okey?

**Pull request closed without merging**
