### PR TITLE
- functional modal

### PR DESCRIPTION
**Pull request by Phanty78**
- fixed a bug in the scrollToRandomSection function

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey! Thanks for contributing to my project

**Comment by JollyJolli** [comment]
Can you please solve the merge issue?

**Comment by JollyJolli** [comment]
Can you please solve the merge issue?

**Comment by Phanty78** [comment]
Conflict resolved

**Comment by JollyJolli** [comment]
Perfect! Happy contributing!

**Pull request merged**
