### PR TITLE
Add 'About Us' section to introduce HacktoberWall and its owners

### PR DESCRIPTION
**Pull request by MehekFatima**
This PR introduces an "About Us" section to the HacktoberWall project. The new section provides information about the project, its purpose, and background, as well as details about the owners of HacktoberWall. Additionally, the owners' GitHub profile pictures are dynamically fetched using the GitHub API to enhance the visual appeal.

### Changes Made

- **HTML**: Added a new "About Us" section with relevant content.
- **CSS**: Styled the section to ensure it is visually engaging and responsive.
- **JavaScript**: Implemented functionality to fetch and display GitHub profile pictures of the owners.

This PR addresses the following issue: #151

### CODE REVIEW

**Comment by JollyJolli** [comment]
Hey there! Thanks for making this! Only one thing, can you please make that info inside of a card?

**Comment by JollyJolli** [comment]
Please also git pull the new aditions of the repo.

**Review by Phanty78 — CHANGES_REQUESTED** [review]
Seem cool! Can you write your code in non-minify files and then minify them.

**Comment by MehekFatima** [comment]
sure!

**Comment by MehekFatima** [comment]
can i use gulp to minify?

**Comment by Phanty78** [comment]
I'm not familiar with this tool, but if it does the job, no problem.

**Comment by MehekFatima** [comment]
#159 new PR

**Pull request closed without merging**
